/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.techie.microservices.cat.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CatPlacedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7007674769783467726L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CatPlacedEvent\",\"namespace\":\"com.techie.microservices.cat.event\",\"fields\":[{\"name\":\"catNumber\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"string\"},{\"name\":\"userEmail\",\"type\":\"string\"},{\"name\":\"ownerEmail\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CatPlacedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CatPlacedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CatPlacedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CatPlacedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CatPlacedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CatPlacedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CatPlacedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CatPlacedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CatPlacedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence catNumber;
  private java.lang.CharSequence title;
  private java.lang.CharSequence price;
  private java.lang.CharSequence userEmail;
  private java.lang.CharSequence ownerEmail;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CatPlacedEvent() {}

  /**
   * All-args constructor.
   * @param catNumber The new value for catNumber
   * @param title The new value for title
   * @param price The new value for price
   * @param userEmail The new value for userEmail
   * @param ownerEmail The new value for ownerEmail
   */
  public CatPlacedEvent(java.lang.CharSequence catNumber, java.lang.CharSequence title, java.lang.CharSequence price, java.lang.CharSequence userEmail, java.lang.CharSequence ownerEmail) {
    this.catNumber = catNumber;
    this.title = title;
    this.price = price;
    this.userEmail = userEmail;
    this.ownerEmail = ownerEmail;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return catNumber;
    case 1: return title;
    case 2: return price;
    case 3: return userEmail;
    case 4: return ownerEmail;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: catNumber = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: price = (java.lang.CharSequence)value$; break;
    case 3: userEmail = (java.lang.CharSequence)value$; break;
    case 4: ownerEmail = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'catNumber' field.
   * @return The value of the 'catNumber' field.
   */
  public java.lang.CharSequence getCatNumber() {
    return catNumber;
  }


  /**
   * Sets the value of the 'catNumber' field.
   * @param value the value to set.
   */
  public void setCatNumber(java.lang.CharSequence value) {
    this.catNumber = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.CharSequence getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.CharSequence value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'userEmail' field.
   * @return The value of the 'userEmail' field.
   */
  public java.lang.CharSequence getUserEmail() {
    return userEmail;
  }


  /**
   * Sets the value of the 'userEmail' field.
   * @param value the value to set.
   */
  public void setUserEmail(java.lang.CharSequence value) {
    this.userEmail = value;
  }

  /**
   * Gets the value of the 'ownerEmail' field.
   * @return The value of the 'ownerEmail' field.
   */
  public java.lang.CharSequence getOwnerEmail() {
    return ownerEmail;
  }


  /**
   * Sets the value of the 'ownerEmail' field.
   * @param value the value to set.
   */
  public void setOwnerEmail(java.lang.CharSequence value) {
    this.ownerEmail = value;
  }

  /**
   * Creates a new CatPlacedEvent RecordBuilder.
   * @return A new CatPlacedEvent RecordBuilder
   */
  public static CatPlacedEvent.Builder newBuilder() {
    return new CatPlacedEvent.Builder();
  }

  /**
   * Creates a new CatPlacedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CatPlacedEvent RecordBuilder
   */
  public static CatPlacedEvent.Builder newBuilder(CatPlacedEvent.Builder other) {
    if (other == null) {
      return new CatPlacedEvent.Builder();
    } else {
      return new CatPlacedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CatPlacedEvent RecordBuilder by copying an existing CatPlacedEvent instance.
   * @param other The existing instance to copy.
   * @return A new CatPlacedEvent RecordBuilder
   */
  public static CatPlacedEvent.Builder newBuilder(CatPlacedEvent other) {
    if (other == null) {
      return new CatPlacedEvent.Builder();
    } else {
      return new CatPlacedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CatPlacedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CatPlacedEvent>
    implements org.apache.avro.data.RecordBuilder<CatPlacedEvent> {

    private java.lang.CharSequence catNumber;
    private java.lang.CharSequence title;
    private java.lang.CharSequence price;
    private java.lang.CharSequence userEmail;
    private java.lang.CharSequence ownerEmail;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(CatPlacedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.catNumber)) {
        this.catNumber = data().deepCopy(fields()[0].schema(), other.catNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[3].schema(), other.userEmail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.ownerEmail)) {
        this.ownerEmail = data().deepCopy(fields()[4].schema(), other.ownerEmail);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CatPlacedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(CatPlacedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.catNumber)) {
        this.catNumber = data().deepCopy(fields()[0].schema(), other.catNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[3].schema(), other.userEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ownerEmail)) {
        this.ownerEmail = data().deepCopy(fields()[4].schema(), other.ownerEmail);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'catNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCatNumber() {
      return catNumber;
    }


    /**
      * Sets the value of the 'catNumber' field.
      * @param value The value of 'catNumber'.
      * @return This builder.
      */
    public CatPlacedEvent.Builder setCatNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.catNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'catNumber' field has been set.
      * @return True if the 'catNumber' field has been set, false otherwise.
      */
    public boolean hasCatNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'catNumber' field.
      * @return This builder.
      */
    public CatPlacedEvent.Builder clearCatNumber() {
      catNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public CatPlacedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public CatPlacedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.CharSequence getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public CatPlacedEvent.Builder setPrice(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public CatPlacedEvent.Builder clearPrice() {
      price = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserEmail() {
      return userEmail;
    }


    /**
      * Sets the value of the 'userEmail' field.
      * @param value The value of 'userEmail'.
      * @return This builder.
      */
    public CatPlacedEvent.Builder setUserEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.userEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userEmail' field has been set.
      * @return True if the 'userEmail' field has been set, false otherwise.
      */
    public boolean hasUserEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userEmail' field.
      * @return This builder.
      */
    public CatPlacedEvent.Builder clearUserEmail() {
      userEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ownerEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnerEmail() {
      return ownerEmail;
    }


    /**
      * Sets the value of the 'ownerEmail' field.
      * @param value The value of 'ownerEmail'.
      * @return This builder.
      */
    public CatPlacedEvent.Builder setOwnerEmail(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.ownerEmail = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ownerEmail' field has been set.
      * @return True if the 'ownerEmail' field has been set, false otherwise.
      */
    public boolean hasOwnerEmail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ownerEmail' field.
      * @return This builder.
      */
    public CatPlacedEvent.Builder clearOwnerEmail() {
      ownerEmail = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CatPlacedEvent build() {
      try {
        CatPlacedEvent record = new CatPlacedEvent();
        record.catNumber = fieldSetFlags()[0] ? this.catNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.userEmail = fieldSetFlags()[3] ? this.userEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.ownerEmail = fieldSetFlags()[4] ? this.ownerEmail : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CatPlacedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CatPlacedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CatPlacedEvent>
    READER$ = (org.apache.avro.io.DatumReader<CatPlacedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.catNumber);

    out.writeString(this.title);

    out.writeString(this.price);

    out.writeString(this.userEmail);

    out.writeString(this.ownerEmail);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldCat = in.readFieldOrderIfDiff();
    if (fieldCat == null) {
      this.catNumber = in.readString(this.catNumber instanceof Utf8 ? (Utf8)this.catNumber : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.price = in.readString(this.price instanceof Utf8 ? (Utf8)this.price : null);

      this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);

      this.ownerEmail = in.readString(this.ownerEmail instanceof Utf8 ? (Utf8)this.ownerEmail : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldCat[i].pos()) {
        case 0:
          this.catNumber = in.readString(this.catNumber instanceof Utf8 ? (Utf8)this.catNumber : null);
          break;

        case 1:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 2:
          this.price = in.readString(this.price instanceof Utf8 ? (Utf8)this.price : null);
          break;

        case 3:
          this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);
          break;

        case 4:
          this.ownerEmail = in.readString(this.ownerEmail instanceof Utf8 ? (Utf8)this.ownerEmail : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










