apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-mysql-cronjob  # 1. Имя релиза (встроенный объект Helm)
spec:
  schedule: "{{ .Values.cronjob.schedule }}" # 2. Расписание из values.yaml
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-cronjob-container
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}" # 3. Имя и тег образа из values.yaml
              imagePullPolicy: IfNotPresent
              env:
                - name: MYSQL_HOST
                  value: {{ .Values.mysql.host }} # 4. Имя хоста MySQL из values.yaml
                - name: MYSQL_PORT
                  value: "{{ .Values.mysql.port | quote }}" # 5. Порт MySQL из values.yaml
                - name: MYSQL_USER
                  value: {{ .Values.mysql.user }} # 6. Имя пользователя MySQL из values.yaml
                - name: MYSQL_PASSWORD
                  valueFrom: # Значение из секрета Kubernetes
                    secretKeyRef:
                      name: mysql-secrets # Имя секрета (должно быть создано в Kubernetes)
                      key: mysql_root_password # Ключ в секрете
              command:
                - /app/get_databases.sh
          restartPolicy: {{ .Values.cronjob.restartPolicy }} # 7. Политика перезапуска из values.yaml