apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-service
  template:
    metadata:
      labels:
        app: cat-service
    spec:
      containers:
        - name: cat-service
          image: algolov2/cat-service:latest
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
                  name: common-config
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: cat-service-config
            - name: LOGIN_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_SERVICE_URL
                  name: common-config
            - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
                  name: cat-service-config
            - name: PAGE_TITLE
              valueFrom:
                configMapKeyRef:
                  name: cat-service-config
                  key: PAGE_TITLE
---
apiVersion: v1
kind: Service
metadata:
  name: cat-service
spec:
  selector:
    app: cat-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cat-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/cat_service"
  SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.default.svc.cluster.local:8081"
  PAGE_TITLE: "Новый Заголовок"