---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  CAT_SERVICE_URL: "http://cat-service.default.svc.cluster.local:8081"
  LOGIN_SERVICE_URL: "http://login-service.default.svc.cluster.local:8082"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.default.svc.cluster.local:29092"