apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-recent-users
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-recent-users
              image: mysql:8.3.0
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secrets
                      key: mysql_root_password
                - name: MYSQL_DATABASE
                  value: "cat_service"
              command:
                - /bin/sh
                - -c
                - |
                  mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} -e "CALL UpdateRecentUsers();"
          restartPolicy: OnFailure
