apiVersion: batch/v1
kind: CronJob
metadata:
  name: notification-send
  namespace: default
spec:
  # каждый день в 9:00
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl-send
              image: curlimages/curl:7.87.0
              command: ["sh", "-c"]
              args:
                - |
                  echo "== Sending daily notifications via notification-service =="
                  # POST-запрос с query-параметрами: ?recipient=...&message=...
                  curl -X POST \
                       "http://notification-service.default.svc.cluster.local:8083/api/notifications/send?recipient=test@example.com&message=Your+daily+reminder"
                  echo "== Done =="
