apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
type: Opaque
data:
  smtp_host: c2FuZGJveC5zdHBtLm1haWx0cmFwLmlv
  smtp_port: MjUyNQ==
  smtp_user: MGNmNTlkZTQ2YjZhOQ==
  smtp_password: NDg0ZjM4YzhkZDc4YjE=
